name: Minify CSS and deploy to live branch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Wrong domain check
        run: |
          echo "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          if git grep -q -E ${{ secrets.DOMAIN }} -- *.css; then
            echo "Game over man!"
            exit 1
          fi
      - name: Minify CSS
        run: |
          sudo npm install -g minify
          sudo apt-get update
          sudo apt-get -y install moreutils

          minify_file(){
              directory=$1
              basename=$(basename $directory);
              extension="${basename##*.}"
              output="${directory%/*}/"
              filename="${basename%.*}"
              output_path="${output}${filename}.${extension}"
              minify ${directory} | sponge ${output_path}
              echo "Minified ${directory} > ${output_path}"
          }
          
            find ./CSS -type f -iname *base.css | while read fname
                do
                    if [[ "$fname" != *"min."* ]]; then
                        minify_file $fname
                    fi
                done

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          publish_dir: ./
          publish_branch: live
          github_token: ${{ secrets.GITHUB_TOKEN }}